package com.fouriApps.model.AM.common;

import java.util.ArrayList;
import java.util.Map;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 21 14:30:34 IST 2018
// ---------------------------------------------------------------------
public interface DynamicReports_AM extends ApplicationModule {

    Map applicationSessionSetup();

    ArrayList getLOVValues(String tableName, String value, String displayValue,
                           String lookupType, String LovBasedUserBindVariable,
                           String LovBasedUserYn, String dynamicLovlookupType,
                           String userName);
}
