package com.fouriApps.model.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 24 16:59:51 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxfndReportParamsVoImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XxfndReportParamsVoImpl() {
    }

    /**
     * Returns the variable value for b_FuncId.
     * @return variable value for b_FuncId
     */
    public String getb_FuncId() {
        return (String)ensureVariableManager().getVariableValue("b_FuncId");
    }

    /**
     * Sets <code>value</code> for variable b_FuncId.
     * @param value value to bind as b_FuncId
     */
    public void setb_FuncId(String value) {
        ensureVariableManager().setVariableValue("b_FuncId", value);
    }
}
